version: 2
updates:
  - package-ecosystem: gomod
    directory: /backend
    schedule:
      interval: daily
    rebase-strategy: disabled
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    rebase-strategy: disabled
