apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kyverno-playground.fullname" . }}-config
  labels:
    {{- include "kyverno-playground.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{ tpl (.Files.Get "config/config.tmpl") . }}