{{- if .Values.mcp.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kyverno-playground.mcp.fullname" . }}
  labels:
    {{- include "kyverno-playground.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.mcp.replicaCount }}
  selector:
    matchLabels:
      {{- include "kyverno-playground.mcp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kyverno-playground.mcp.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.global.labels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kyverno-playground.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: mcp
          args:
            - mcp
            - --server-port={{ int .Values.mcp.port }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.mcp.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8085
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8085
          env:
          - name: TUF_ROOT
            value: {{ .Values.tufRootMountPath }}
          volumeMounts:
            - mountPath: {{ .Values.tufRootMountPath }}
              name: sigstore
          resources:
            {{- toYaml .Values.mcp.resources | nindent 12 }}
      volumes:
      - name: sigstore
        emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
