before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    binary: kyverno-playground
    flags:
      - -trimpath
    ldflags:
      - -s -w

kos:
  - repository: ghcr.io/kyverno/playground
    tags:
      - '{{.Tag}}'
    bare: true
    preserve_import_paths: false
    sbom: none
    platforms:
      - all
    flags:
      - -trimpath
    ldflags:
      - -s -w

docker_signs:
  - artifacts: all
    args:
      - 'sign'
      - '${artifact}'
      - "--yes"

archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'

checksum:
  name_template: 'checksums.txt'

source:
  enabled: true

sboms:
  - artifacts: archive
  - id: source
    artifacts: source

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
