ingress:
  enabled: true
  # annotations:
  #   nginx.ingress.kubernetes.io/rewrite-target: $1$2
  hosts:
    - host: ~
      paths:
        # - path: /playground(/|$)(.*)
        - path: /
          pathType: Prefix
