kubernetes:
  version: '1.27'

context:
  username: ''
  groups: []
  roles: []
  clusterRoles: []
  namespaceLabels: {}
  operation: CREATE
  dryRun: false

variables:
  hosts: "[\"www.github.com\", \"www.kyverno.com\", \"www.nirmata.com\"]"