name: ci

on:
  pull_request:
    branches:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.0
      - name: Set up Go
        uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
      - name: Check go.mod
        run: cd backend && go mod tidy && git diff --exit-code
      - name: Build
        run: make build-backend
      - name: Check code format
        run: |
          diff=$(gofmt -s -d backend)
          if [[ -n "${diff}" ]]; then echo "${diff}"; exit 1; fi

  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.0
      - name: Build
        run: make build-frontend
