name: codecov

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: backend/go.mod
          cache-dependency-path: backend/go.sum
      - name: Build assets
        run: |
          set -e
          make build-backend-assets
      - name: Test
        run: |
          set -e
          make test-backend
      - name: Upload Report to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v6.0.2
        with:
          file: ./backend/coverage.out
          fail_ci_if_error: true
          verbose: true
          use_oidc: true
